### PR TITLE
Blacklist setLifecycleOwner method in databinding field parsing, fixes #412

### LINKED ISSUE #412: lifecycleOwner  property with databinding auto generated models
Hi,

Thanks for this great library!

Having an issue after upgrading to Android Studio 3.1 which introduce the Android Architecture Components. If my layout includes another layout the `setLifecycleOwner` method is being overridden in the generated binding class and then being treated as an attribute. This is causing a build time exception while the generated (*Model_) class is trying to use `BR.lifecycleOwner` which doesn't really exists.

### PR DESCRIPTION
**Pull request by ngsilverman**
ViewDataBinding subclasses can now override the setLifecycleOwner method causing it to be erroneously detected as a model field. This fix introduces a field blacklist to ignore this method and possibly others in the future.

To reproduce the issue and create a test for it I had to update the Android plugin version which forced me to also update Gradle, the target SDK, and the paging library. I removed the buildToolsVersion declarations to remove a warning (the build tools version is now provided by the Android plugin from what I understand).

### CODE REVIEW

File: epoxy-pagingsample/src/main/java/com/airbnb/epoxy/pagingsample/PagingSampleActivity.kt [hunk 1]
```diff
@@ -51,8 +51,8 @@ class PagingSampleActivity : AppCompatActivity() {
                             setPrefetchDistance(50)
                             build()
                         }).run {
-                    setMainThreadExecutor(UiThreadExecutor)
-                    setBackgroundThreadExecutor(AsyncTask.THREAD_POOL_EXECUTOR)
+                    setNotifyExecutor(UiThreadExecutor)
+                    setFetchExecutor(AsyncTask.THREAD_POOL_EXECUTOR)
```
Comment (ngsilverman) [inline epoxy-pagingsample/src/main/java/com/airbnb/epoxy/pagingsample/PagingSampleActivity.kt]: These methods were renamed, see https://developer.android.com/topic/libraries/architecture/release-notes.html#paging.

File: epoxy-processor/src/main/java/com/airbnb/epoxy/DataBindingModelInfo.kt [hunk 2]
```diff
@@ -10,13 +10,13 @@ internal class DataBindingModelInfo(
...
-         val moduleName: String,
+        val moduleName: String,
         private val layoutPrefix: String = ""
 ) : GeneratedModelInfo() {
     private val dataBindingClassName: ClassName
 
-    val dataBindingClassElement: Element?
-        get() = getElementByName(dataBindingClassName, elementUtils, typeUtils)
+    private val dataBindingClassElement: TypeElement?
+        get() = getElementByName(dataBindingClassName, elementUtils, typeUtils) as TypeElement?
```
Comment (elihart) [inline epoxy-processor/src/main/java/com/airbnb/epoxy/DataBindingModelInfo.kt]: should this be `as?` instead?

Comment (ngsilverman) [reply epoxy-processor/src/main/java/com/airbnb/epoxy/DataBindingModelInfo.kt]: @elihart I'm thinking: if `getElementByName` doesn't return a `TypeElement` or `null` then something unexpected is happening since we're passing it a `ClassName`. In fact maybe it would make more sense to change the return type of `getElementByName(ClassName name, Elements elements, Types types)`. Thoughts?

Comment (ngsilverman) [reply epoxy-processor/src/main/java/com/airbnb/epoxy/DataBindingModelInfo.kt]: I changed the return type to `TypeElement` and everything still builds and all tests are passing so seems reasonable.
